# Generated by Django 4.1.4 on 2023-02-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=50),
        ),
    ]
