# Generated by Django 4.1.4 on 2023-03-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_useraccount_userid_useraccount_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phc',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='emil',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
