# Generated by Django 5.0 on 2024-04-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filetype',
            field=models.CharField(max_length=10),
        ),
    ]
