# Generated by Django 4.1.4 on 2023-03-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_useraccount_panchayath_remove_useraccount_phc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='emil',
            new_name='email',
        ),
    ]
