# Generated by Django 5.0 on 2024-02-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_emil_useraccount_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('username', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=20)),
                ('status', models.IntegerField(blank=True)),
                ('posts', models.IntegerField(blank=True)),
                ('flowr', models.IntegerField(blank=True)),
                ('flows', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
