# Generated by Django 5.0 on 2024-04-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comments_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
