# Generated by Django 5.0 on 2024-02-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_flowr_alter_user_flows_alter_user_posts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwd',
            new_name='password',
        ),
    ]
