# Generated by Django 5.0 on 2024-02-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_passwd_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='user',
            name='u_img',
            field=models.ImageField(default='blank_user.png', upload_to='user_img'),
        ),
    ]
